package com.myspend.app;
import android.app.*;import android.os.*;import android.content.*;import android.database.Cursor;import android.graphics.Color;import android.provider.Settings;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;
public class MainActivity extends Activity{
 SpendDb db; LinearLayout root,list; TextView spent,income,balance; int navy=Color.rgb(17,24,39);
 public void onCreate(Bundle b){super.onCreate(b);db=new SpendDb(this);build();refresh();}
 TextView tv(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(navy);v.setPadding(8,8,8,8);return v;}
 Button btn(String s){Button b=new Button(this);b.setText(s);return b;}
 public void build(){ScrollView sc=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(36,30,36,40);root.setBackgroundColor(Color.rgb(245,247,250));TextView title=tv("My Spend",30);title.setTypeface(null,1);root.addView(title);root.addView(tv("All your spending. One place.",15)); spent=tv("",27);root.addView(tv("SPENT",12));root.addView(spent); LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);income=tv("",16);balance=tv("",16);row.addView(income,new LinearLayout.LayoutParams(0,-2,1));row.addView(balance,new LinearLayout.LayoutParams(0,-2,1));root.addView(row);Button add=btn("+ Add transaction");add.setOnClickListener(v->addDialog());root.addView(add);Button access=btn("Enable automatic UPI notification detection");access.setOnClickListener(v->startActivity(new Intent("android.settings.ACTION_NOTIFICATION_LISTENER_SETTINGS")));root.addView(access);TextView h=tv("Recent transactions",20);h.setTypeface(null,1);root.addView(h);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);root.addView(tv("V1 • Offline-first • Data stored on this device",12));sc.addView(root);setContentView(sc);}
 void refresh(){double e=db.sum("expense"),i=db.sum("income");spent.setText(money(e));income.setText("Income\n"+money(i));balance.setText("Net\n"+money(i-e));list.removeAllViews();Cursor c=db.all();SimpleDateFormat f=new SimpleDateFormat("dd MMM, h:mm a",Locale.getDefault());while(c.moveToNext()){String kind=c.getString(c.getColumnIndexOrThrow("kind"));String sign=kind.equals("expense")?"−":"+";TextView x=tv(c.getString(c.getColumnIndexOrThrow("merchant"))+"\n"+c.getString(c.getColumnIndexOrThrow("category"))+" • "+f.format(new Date(c.getLong(c.getColumnIndexOrThrow("ts"))))+"\n"+sign+money(c.getDouble(c.getColumnIndexOrThrow("amount"))),16);x.setBackgroundColor(Color.WHITE);x.setPadding(24,18,24,18);list.addView(x,new LinearLayout.LayoutParams(-1,-2));}c.close();}
 String money(double x){return String.format(Locale.US,"₹%,.2f",x);}
 void addDialog(){LinearLayout p=new LinearLayout(this);p.setPadding(30,0,30,0);p.setOrientation(LinearLayout.VERTICAL);EditText m=new EditText(this);m.setHint("Merchant / note");EditText a=new EditText(this);a.setHint("Amount");a.setInputType(2|8192);Spinner cat=new Spinner(this);String[] cs={"Food","Shopping","Travel","Bills","Business","Transfer","Other"};cat.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,cs));p.addView(m);p.addView(a);p.addView(cat);new AlertDialog.Builder(this).setTitle("Add expense").setView(p).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{try{double n=Double.parseDouble(a.getText().toString());long t=System.currentTimeMillis();db.add(t,n,"expense",m.getText().toString().trim().isEmpty()?"Manual expense":m.getText().toString(),cat.getSelectedItem().toString(),"manual","manual|"+t);refresh();}catch(Exception ignored){}}).show();}
 protected void onResume(){super.onResume();if(db!=null)refresh();}
}
