package com.myspend.app;

import android.app.*;import android.os.*;import android.content.*;import android.provider.Settings;import android.database.Cursor;import android.graphics.*;import android.graphics.drawable.*;import android.net.Uri;import android.view.*;import android.widget.*;import java.io.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
 SpendDb db; LinearLayout page; int ink=Color.rgb(16,33,43), muted=Color.rgb(107,125,135), blue=Color.rgb(8,105,135), green=Color.rgb(24,185,133), bg=Color.rgb(244,247,248); final int IMPORT_CSV=44;
 public void onCreate(Bundle b){super.onCreate(b);db=new SpendDb(this);showHome();}
 TextView t(String s,float z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
 GradientDrawable box(int color,float r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(r));return g;}
 int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);} LinearLayout.LayoutParams mp(){return new LinearLayout.LayoutParams(-1,-2);}
 void pad(View v,int a,int b,int c,int d){v.setPadding(dp(a),dp(b),dp(c),dp(d));}
 TextView chip(String s){TextView v=t(s,13,ink);v.setGravity(Gravity.CENTER);pad(v,14,8,14,8);v.setBackground(box(Color.WHITE,22));return v;}
 void shell(String title){LinearLayout outer=new LinearLayout(this);outer.setOrientation(LinearLayout.VERTICAL);outer.setBackgroundColor(bg);ScrollView sc=new ScrollView(this);page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);pad(page,20,20,20,100);sc.addView(page);outer.addView(sc,new LinearLayout.LayoutParams(-1,0,1));View nv=nav();outer.addView(nv);setContentView(outer); nv.setOnApplyWindowInsetsListener((v,in)->{int bottom=in.getSystemWindowInsetBottom();v.setPadding(v.getPaddingLeft(),v.getPaddingTop(),v.getPaddingRight(),Math.max(bottom,dp(8)));return in;}); nv.requestApplyInsets();}
 View nav(){LinearLayout n=new LinearLayout(this);n.setGravity(Gravity.CENTER);n.setBackgroundColor(Color.WHITE);String[] a={"⌂\nHome","≡\nTransactions","＋","▥\nAnalytics","⚙\nSettings"};for(int i=0;i<a.length;i++){TextView v=t(a[i],i==2?26:11,i==2?Color.WHITE:muted);v.setGravity(Gravity.CENTER);if(i==2){v.setBackground(box(blue,40));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(56),dp(56));p.setMargins(dp(5),dp(5),dp(5),dp(5));n.addView(v,p);}else{final int k=i;v.setOnClickListener(x->{if(k==0)showHome();else if(k==1)showTransactions();else if(k==3)showAnalytics();else if(k==4)showSettings();});n.addView(v,new LinearLayout.LayoutParams(0,dp(66),1));}}return n;}
 void header(String big,String small){TextView h=t(big,27,ink);h.setTypeface(null,Typeface.BOLD);page.addView(h);TextView s=t(small,14,muted);page.addView(s);Space z=new Space(this);page.addView(z,new LinearLayout.LayoutParams(1,dp(18)));}
 public void showHome(){shell("Home");header("Good evening","Let’s manage your money");LinearLayout periods=new LinearLayout(this);for(String s:new String[]{"Today","Week","Month","Year"})periods.addView(chip(s),new LinearLayout.LayoutParams(0,-2,1));page.addView(periods);Space q=new Space(this);page.addView(q,new LinearLayout.LayoutParams(1,dp(14)));double e=db.sum("expense"),i=db.sum("income");LinearLayout hero=new LinearLayout(this);hero.setOrientation(LinearLayout.VERTICAL);hero.setBackground(box(blue,22));pad(hero,22,20,22,20);hero.addView(t("YOUR BALANCE",12,0xFFD9F6FF));TextView bal=t(money(i-e),31,Color.WHITE);bal.setTypeface(null,Typeface.BOLD);hero.addView(bal);hero.addView(t("Private • stored on this device",12,0xFFD9F6FF));page.addView(hero);LinearLayout stats=new LinearLayout(this);stats.setPadding(0,dp(12),0,0);stats.addView(stat("↑  Income",money(i),green),new LinearLayout.LayoutParams(0,-2,1));stats.addView(stat("↓  Spending",money(e),0xFFE45858),new LinearLayout.LayoutParams(0,-2,1));page.addView(stats);section("Spending by category");page.addView(new CategoryView(this,db));section("Recent transactions");addRecent(5);Button add=new Button(this);add.setText("＋ Add transaction");add.setTextColor(Color.WHITE);add.setTextSize(16);add.setBackground(box(blue,18));add.setOnClickListener(v->addDialog());page.addView(add,new LinearLayout.LayoutParams(-1,dp(54)));}
 View stat(String a,String b,int c){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setBackground(box(Color.WHITE,18));pad(x,16,14,16,14);TextView p=t(a,13,c);p.setTypeface(null,Typeface.BOLD);x.addView(p);TextView v=t(b,19,ink);v.setTypeface(null,Typeface.BOLD);x.addView(v);LinearLayout.LayoutParams lp=(LinearLayout.LayoutParams)x.getLayoutParams();return x;}
 void section(String s){TextView h=t(s,19,ink);h.setTypeface(null,Typeface.BOLD);h.setPadding(0,dp(24),0,dp(10));page.addView(h);}
 void addRecent(int max){Cursor c=db.all();int n=0;while(c.moveToNext()&&n++<max)page.addView(txRow(c));c.close();if(n==0){TextView empty=t("No transactions yet. Tap + Add transaction to start.",14,muted);empty.setGravity(Gravity.CENTER);empty.setBackground(box(Color.WHITE,18));pad(empty,20,28,20,28);page.addView(empty);}}
 View txRow(Cursor c){LinearLayout x=new LinearLayout(this);x.setGravity(Gravity.CENTER_VERTICAL);x.setBackground(box(Color.WHITE,16));pad(x,14,12,14,12);TextView icon=t(icon(c.getString(c.getColumnIndexOrThrow("category"))),20,Color.WHITE);icon.setGravity(Gravity.CENTER);icon.setBackground(box(blue,14));x.addView(icon,new LinearLayout.LayoutParams(dp(44),dp(44)));LinearLayout mid=new LinearLayout(this);mid.setOrientation(LinearLayout.VERTICAL);mid.setPadding(dp(12),0,dp(6),0);String merchant=c.getString(c.getColumnIndexOrThrow("merchant"));TextView m=t(merchant,15,ink);m.setTypeface(null,Typeface.BOLD);mid.addView(m);mid.addView(t(c.getString(c.getColumnIndexOrThrow("category"))+" • "+new SimpleDateFormat("dd MMM, h:mm a",Locale.getDefault()).format(new Date(c.getLong(c.getColumnIndexOrThrow("ts")))),12,muted));x.addView(mid,new LinearLayout.LayoutParams(0,-2,1));boolean ex="expense".equals(c.getString(c.getColumnIndexOrThrow("kind")));TextView amt=t((ex?"− ":"+ ")+money(c.getDouble(c.getColumnIndexOrThrow("amount"))),15,ex?ink:green);amt.setTypeface(null,Typeface.BOLD);x.addView(amt);LinearLayout.LayoutParams lp=mp();lp.setMargins(0,0,0,dp(8));x.setLayoutParams(lp);return x;}
 String icon(String c){if(c.equals("Food"))return "🍴";if(c.equals("Shopping"))return "▣";if(c.equals("Travel"))return "✈";if(c.equals("Bills"))return "⚡";if(c.equals("Business"))return "▤";return "₹";}
 public void showTransactions(){shell("Transactions");header("Transactions","Everything in one clean timeline");LinearLayout f=new LinearLayout(this);for(String s:new String[]{"All","Income","Expense","Transfer"})f.addView(chip(s),new LinearLayout.LayoutParams(0,-2,1));page.addView(f);section("History");addRecent(999);}
 public void showAnalytics(){shell("Analytics");header("Analytics","Understand where your money goes");double e=db.sum("expense");LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setBackground(box(Color.WHITE,20));pad(card,18,18,18,18);card.addView(t("TOTAL SPENDING",12,muted));TextView total=t(money(e),28,ink);total.setTypeface(null,Typeface.BOLD);card.addView(total);page.addView(card);section("Category breakdown");String[] cs={"Food","Shopping","Bills","Travel","Business","Transfer","Other"};for(String c:cs){double v=db.sumCategory(c);if(v>0){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);TextView a=t(icon(c)+"  "+c,15,ink);r.addView(a,new LinearLayout.LayoutParams(0,dp(46),1));TextView b=t(money(v)+(e>0?"  •  "+Math.round(v*100/e)+"%":""),14,muted);r.addView(b);page.addView(r);}}page.addView(new CategoryView(this,db));}
 public void showSettings(){shell("Settings");header("Settings","Private, local and under your control");section("Automatic tracking");info("Supported payment notifications","PhonePe • Paytm • BHIM • MobiKwik • Google Pay. My Spend records only recognizable payment notifications after you enable access.");android.widget.Switch sw=new android.widget.Switch(this);sw.setText("Automatic transaction tracking");sw.setTextSize(15);sw.setChecked(getSharedPreferences("prefs",MODE_PRIVATE).getBoolean("auto_tracking",false));sw.setPadding(dp(12),dp(14),dp(12),dp(14));sw.setBackground(box(Color.WHITE,16));sw.setOnCheckedChangeListener((b,on)->{getSharedPreferences("prefs",MODE_PRIVATE).edit().putBoolean("auto_tracking",on).apply();if(on&&!notificationAccess()){Toast.makeText(this,"Enable My Spend on the next Android screen",Toast.LENGTH_LONG).show();startActivity(new Intent("android.settings.ACTION_NOTIFICATION_LISTENER_SETTINGS"));}});page.addView(sw);Button access=new Button(this);access.setText(notificationAccess()?"Notification access: ON":"Enable notification access");access.setOnClickListener(v->startActivity(new Intent("android.settings.ACTION_NOTIFICATION_LISTENER_SETTINGS")));page.addView(access);info("What this does","Payment apps keep their private databases private. My Spend only reads notifications Android shares after your permission and converts recognized successful payments into local records.");section("Data & privacy");info("✓ No Internet permission","My Spend does not upload your transaction database.");info("✓ No SMS access","The app does not read your messages.");info("✓ No accessibility access","No broad device-control permission is requested.");section("Import");Button b=new Button(this);b.setText("Import CSV statement");b.setOnClickListener(v->{Intent in=new Intent(Intent.ACTION_OPEN_DOCUMENT);in.setType("text/*");in.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(in,IMPORT_CSV);});page.addView(b);page.addView(t("CSV columns supported: date, merchant, amount, type, category. You can also use: merchant, amount, category.",12,muted));section("About");info("My Spend V1.2 Auto","Personal finance tracker • com.myspend.app");}
 boolean notificationAccess(){String s=Settings.Secure.getString(getContentResolver(),"enabled_notification_listeners");return s!=null&&s.contains(getPackageName());}
 void info(String a,String b){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setBackground(box(Color.WHITE,16));pad(x,16,13,16,13);TextView aa=t(a,15,ink);aa.setTypeface(null,Typeface.BOLD);x.addView(aa);x.addView(t(b,12,muted));LinearLayout.LayoutParams lp=mp();lp.setMargins(0,0,0,dp(8));page.addView(x,lp);}
 void addDialog(){LinearLayout p=new LinearLayout(this);p.setPadding(dp(24),0,dp(24),0);p.setOrientation(LinearLayout.VERTICAL);EditText m=new EditText(this);m.setHint("Merchant / note");EditText a=new EditText(this);a.setHint("Amount");a.setInputType(2|8192);Spinner kind=new Spinner(this);kind.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Expense","Income"}));Spinner cat=new Spinner(this);String[] cs={"Food","Shopping","Travel","Bills","Business","Transfer","Other"};cat.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,cs));p.addView(m);p.addView(a);p.addView(kind);p.addView(cat);new AlertDialog.Builder(this).setTitle("Add transaction").setView(p).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{try{double n=Double.parseDouble(a.getText().toString());long ts=System.currentTimeMillis();String k=kind.getSelectedItemPosition()==0?"expense":"income";String name=m.getText().toString().trim();db.add(ts,n,k,name.isEmpty()?"Manual transaction":name,cat.getSelectedItem().toString(),"manual","manual|"+ts);showHome();}catch(Exception z){Toast.makeText(this,"Enter a valid amount",Toast.LENGTH_SHORT).show();}}).show();}
 protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==IMPORT_CSV&&c==RESULT_OK&&data!=null){int count=importCsv(data.getData());Toast.makeText(this,count+" transactions imported",Toast.LENGTH_LONG).show();showHome();}}
 int importCsv(Uri u){int count=0;try(BufferedReader br=new BufferedReader(new InputStreamReader(getContentResolver().openInputStream(u)))){String line;boolean first=true;while((line=br.readLine())!=null){if(first&&line.toLowerCase().contains("amount")){first=false;continue;}first=false;String[] p=line.split(",");if(p.length<2)continue;String merchant;double amount;String kind="expense",cat="Other";try{if(p.length>=5){merchant=p[1].trim();amount=Math.abs(Double.parseDouble(p[2].replace("₹","").trim()));kind=p[3].toLowerCase().contains("income")||p[3].toLowerCase().contains("credit")?"income":"expense";cat=p[4].trim();}else{merchant=p[0].trim();amount=Math.abs(Double.parseDouble(p[1].replace("₹","").trim()));if(p.length>2)cat=p[2].trim();}long ts=System.currentTimeMillis()+count;if(db.add(ts,amount,kind,merchant,cat,"csv","csv|"+merchant+"|"+amount+"|"+ts))count++;}catch(Exception ignored){}}}catch(Exception e){Toast.makeText(this,"Could not read this CSV",Toast.LENGTH_LONG).show();}return count;}
 String money(double x){return String.format(new Locale("en","IN"),"₹%,.0f",x);}
 protected void onResume(){super.onResume();}
 static class CategoryView extends View {SpendDb db;Paint p=new Paint(1);String[] cs={"Food","Shopping","Bills","Travel","Business","Other"};int[] colors={0xFF11AFC3,0xFFFF6B4A,0xFFFFB72B,0xFF18B985,0xFF7559D9,0xFFB8C2C8};CategoryView(Context c,SpendDb d){super(c);db=d;setMinimumHeight((int)(190*c.getResources().getDisplayMetrics().density));}protected void onDraw(Canvas c){super.onDraw(c);float den=getResources().getDisplayMetrics().density,cx=85*den,cy=90*den,r=58*den;double total=db.sum("expense");if(total<=0){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(18*den);p.setColor(0xFFDDE5E8);c.drawCircle(cx,cy,r,p);p.setStyle(Paint.Style.FILL);p.setColor(0xFF6B7D87);p.setTextSize(13*den);c.drawText("No spending",47*den,94*den,p);return;}RectF oval=new RectF(cx-r,cy-r,cx+r,cy+r);float start=-90;for(int i=0;i<cs.length;i++){double v=db.sumCategory(cs[i]);float sweep=(float)(v/total*360);p.setColor(colors[i]);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(18*den);c.drawArc(oval,start,sweep,false,p);start+=sweep;}p.setStyle(Paint.Style.FILL);p.setColor(0xFF10212B);p.setTextSize(14*den);c.drawText("Spending",57*den,87*den,p);p.setTextSize(12*den);c.drawText(String.format(new Locale("en","IN"),"₹%,.0f",total),58*den,105*den,p);}}
}
